# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Specify package manager to be pip for Python
    directory: "/" # Location of package manifests (e.g., where requirements.txt is)
    schedule:
      interval: "weekly" # How often to check for updates
